"""
Additional database schema for complete functionality
"""

ADDITIONAL_TABLES = """
-- Threat alerts table
CREATE TABLE threat_alerts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path VARCHAR2(4000) NOT NULL,
    event_type VARCHAR2(50),
    classification VARCHAR2(50) NOT NULL,
    threat_score NUMBER(3,2),
    alert_data CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    acknowledged CHAR(1) DEFAULT 'N',
    acknowledged_by VARCHAR2(255),
    acknowledged_at TIMESTAMP
) TABLESPACE USERS;

-- System events table
CREATE TABLE system_events (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR2(100) NOT NULL,
    event_category VARCHAR2(50),
    severity VARCHAR2(20),
    source_component VARCHAR2(100),
    event_message CLOB,
    event_data CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE USERS;

-- Configuration history table
CREATE TABLE config_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR2(255) NOT NULL,
    old_value CLOB,
    new_value CLOB,
    changed_by VARCHAR2(255),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    change_reason VARCHAR2(500)
) TABLESPACE USERS;

-- Performance metrics table
CREATE TABLE performance_metrics (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name VARCHAR2(100) NOT NULL,
    metric_value NUMBER,
    metric_unit VARCHAR2(20),
    component VARCHAR2(100),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE USERS;

-- User sessions table
CREATE TABLE user_sessions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR2(255) UNIQUE NOT NULL,
    username VARCHAR2(255) NOT NULL,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'ACTIVE'
) TABLESPACE USERS;

-- API access logs table
CREATE TABLE api_access_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint VARCHAR2(255) NOT NULL,
    method VARCHAR2(10) NOT NULL,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    request_data CLOB,
    response_status NUMBER,
    response_time NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE USERS;

-- Create indexes for performance
CREATE INDEX idx_threat_alerts_created ON threat_alerts(created_at);
CREATE INDEX idx_threat_alerts_classification ON threat_alerts(classification);
CREATE INDEX idx_system_events_type ON system_events(event_type);
CREATE INDEX idx_system_events_created ON system_events(created_at);
CREATE INDEX idx_config_history_key ON config_history(config_key);
CREATE INDEX idx_performance_metrics_name ON performance_metrics(metric_name);
CREATE INDEX idx_performance_metrics_recorded ON performance_metrics(recorded_at);
CREATE INDEX idx_user_sessions_username ON user_sessions(username);
CREATE INDEX idx_user_sessions_status ON user_sessions(status);
CREATE INDEX idx_api_logs_endpoint ON api_access_logs(endpoint);
CREATE INDEX idx_api_logs_created ON api_access_logs(created_at);
"""
